name: silent_camera
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Camera
  camera: ^0.11.0+2
  video_player: ^2.9.1

  screenshot: ^3.0.0
  image_gallery_saver: ^2.0.3
  image_picker: ^1.1.2

  # 状態管理
  flutter_hooks: ^0.20.5
  hooks_riverpod: ^2.6.1
  flutter_riverpod: ^2.6.1
  json_annotation: ^4.9.0
  riverpod_annotation: ^2.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # コードチェック
  flutter_lints: ^5.0.0
  pedantic_mono: ^1.29.0
  riverpod_lint: ^2.6.2

  #generated code
  freezed: ^2.5.7
  build_runner: ^2.4.13
  json_serializable: ^6.8.0
  riverpod_generator: ^2.6.2

flutter:
  uses-material-design: true
